// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWP2eO5csXZiq6KLG2BCBQo68QjY8eV58',
    appId: '1:927030021351:web:22239439e0e017d689e642',
    messagingSenderId: '927030021351',
    projectId: 'chatapp-fc371',
    authDomain: 'chatapp-fc371.firebaseapp.com',
    storageBucket: 'chatapp-fc371.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-bK_xzV0bhVbykaI0ei8eovYTunoGQ5Y',
    appId: '1:927030021351:android:e6c29fc24ad24a6589e642',
    messagingSenderId: '927030021351',
    projectId: 'chatapp-fc371',
    storageBucket: 'chatapp-fc371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBmYqGYPUi3MjTGn6a7Um5Bi22zN9ymbc',
    appId: '1:927030021351:ios:e3897968117f83c389e642',
    messagingSenderId: '927030021351',
    projectId: 'chatapp-fc371',
    storageBucket: 'chatapp-fc371.firebasestorage.app',
    iosBundleId: 'com.svh.chatapp',
  );
}
